name: "YukNgaji"
description: "Aplikasi Al-Quran dan Jadwal Sholat"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.0.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  geolocator: ^12.0.0
  geocoding: ^2.1.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.0
  sqflite: ^2.3.0
  path: ^1.8.3
  hijri:   # Use the latest version from pub.dev
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Leadership Skill Icon.jpg"

flutter:
  uses-material-design: true

  # Correct placement of assets
  assets:
    - assets/mosque_background.jpg # Path to your background image
    - assets/sounds/adzan.mp3
    - assets/sounds/alarm.mp3
    - assets/sounds/notification.mp3

  # Fonts section (already correct)
#  fonts:
#    - family: Arabic
#      fonts:
#        - asset: fonts/arabic_font.ttf